### admin modify user
PATCH http://localhost:3000/user/admin/modify
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDdjOTMwZjc5MWRjZTMyZTFlZGRhOGQiLCJlbWFpbEFkZHJlc3MiOiJhZG1pbkBnbWFpbC5jb20iLCJhY2NvdW50VHlwZSI6IkFETUlOIiwiaWF0IjoxNjg1ODg1OTAwfQ.48B9lw5bzo-WCdszebstcnhC8asiK3CTEgj0a5Z-lyk

{
    "emailAddress": "dr2@gmail.com",
    "isBlocked": false,
    "address": "Lagos, Nigeria"
}

### user modify user
PATCH http://localhost:3000/user/modify
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDdjOTcxODJkMjcwODlkZDE4NDc0MWIiLCJlbWFpbEFkZHJlc3MiOiJkckBnbWFpbC5jb20iLCJhY2NvdW50VHlwZSI6IkRSSVZFUiIsImlhdCI6MTY4NTg4NjkzOX0.n0NdQ8vsnt_FmnNyaUcYyOeTRvdDTZUZt0vbGjM7Ds8

{
    "emailAddress": "dr@gmail.com",
    "address": "Bornu, Nigeria"
}

### register car
POST http://localhost:3000/user/driver/register-car
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDdjYTg2YzBhNDAzMzJjODllMWVlZDUiLCJlbWFpbEFkZHJlc3MiOiJkcjRAZ21haWwuY29tIiwiYWNjb3VudFR5cGUiOiJEUklWRVIiLCJpYXQiOjE2ODU4OTExODV9.bykNgcQ6SoKZqHy30g3nfG71fsISGp1Swk6wSJVXbY4

{
    "make": "Ford",
    "model": "Ranger",
    "color": "white",
    "numberPlate": "233 4 422",
    "capacity": 1
}

### unregister car
PATCH http://localhost:3000/user/driver/unregister-car/233%20422
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDdjOTcxODJkMjcwODlkZDE4NDc0MWIiLCJlbWFpbEFkZHJlc3MiOiJkckBnbWFpbC5jb20iLCJhY2NvdW50VHlwZSI6IkRSSVZFUiIsImlhdCI6MTY4NTg4OTA3Mn0.__hp4yhRiUsULhvA96SYqBeR8wM_Q_LkWjub5dkZUTs

### request ride
POST http://localhost:3000/user/rider/request-ride
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDdjOTczNzJkMjcwODlkZDE4NDc0MjUiLCJlbWFpbEFkZHJlc3MiOiJyaUBnbWFpbC5jb20iLCJhY2NvdW50VHlwZSI6IlJJREVSIiwiaWF0IjoxNjg1ODkxMzI1fQ.Le_ulR4tpYCigk2njT54nWA2tvtcQWbt_y0j0bl9Ba8

{
    "pickupPoint": "My Location",
    "destination": "My Destination"
}

### find rides
GET http://localhost:3000/user/driver/find-rides
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDdjOTcxODJkMjcwODlkZDE4NDc0MWIiLCJlbWFpbEFkZHJlc3MiOiJkckBnbWFpbC5jb20iLCJhY2NvdW50VHlwZSI6IkRSSVZFUiIsImlhdCI6MTY4NTg4ODY0Mn0.OruLpXfC2n8j43j54luzEW5_CxJXD9Xd2SmPI1PG2hM

### accept ride
PATCH http://localhost:3000/user/driver/accept-ride/647cad2e85a2de2507c13c51
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDdjYTg2YzBhNDAzMzJjODllMWVlZDUiLCJlbWFpbEFkZHJlc3MiOiJkcjRAZ21haWwuY29tIiwiYWNjb3VudFR5cGUiOiJEUklWRVIiLCJpYXQiOjE2ODU4OTExODV9.bykNgcQ6SoKZqHy30g3nfG71fsISGp1Swk6wSJVXbY4

### get driver's uncompleted rides
GET http://localhost:3000/user/driver/uncompleted-rides
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDdjYTg2YzBhNDAzMzJjODllMWVlZDUiLCJlbWFpbEFkZHJlc3MiOiJkcjRAZ21haWwuY29tIiwiYWNjb3VudFR5cGUiOiJEUklWRVIiLCJpYXQiOjE2ODU4OTExODV9.bykNgcQ6SoKZqHy30g3nfG71fsISGp1Swk6wSJVXbY4

### start ride
PATCH http://localhost:3000/user/driver/start-ride/647cad2e85a2de2507c13c51
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDdjYTg2YzBhNDAzMzJjODllMWVlZDUiLCJlbWFpbEFkZHJlc3MiOiJkcjRAZ21haWwuY29tIiwiYWNjb3VudFR5cGUiOiJEUklWRVIiLCJpYXQiOjE2ODU4OTExODV9.bykNgcQ6SoKZqHy30g3nfG71fsISGp1Swk6wSJVXbY4

### driver end ride
GET http://localhost:3000/user/driver/end-ride/647cad2e85a2de2507c13c51
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDdjYTg2YzBhNDAzMzJjODllMWVlZDUiLCJlbWFpbEFkZHJlc3MiOiJkcjRAZ21haWwuY29tIiwiYWNjb3VudFR5cGUiOiJEUklWRVIiLCJpYXQiOjE2ODU4OTExODV9.bykNgcQ6SoKZqHy30g3nfG71fsISGp1Swk6wSJVXbY4

### rider end ride
GET http://localhost:3000/user/rider/end-ride
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDdjOTczNzJkMjcwODlkZDE4NDc0MjUiLCJlbWFpbEFkZHJlc3MiOiJyaUBnbWFpbC5jb20iLCJhY2NvdW50VHlwZSI6IlJJREVSIiwiaWF0IjoxNjg1ODg3ODUxfQ.cUbqARZLWuQqmZu_0iMQv4Ck4KVWVJrW1NqTQxKAIAY
