### NB: Response format { message: string, status: number, [key: string]: any } for every route

### signup
### You need to sign up before being able other app feature
### provide emailAddress, firstName, lastName, password, address, contact, accountType as request body
### send it as a post request with the Content Type header to the below route
### response will be { createdUser: UserType  } or { message: "Error info" }
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "emailAddress": "dr5@gmail.com",
    "firstName": "Olan",
    "lastName": "Yusuf",
    "password": "12345678",
    "address": "Lagos, Nigeria",
    "contact": "+2349048734555",
    "accountType": "DRIVER"
}

### signin
### To access any other route, you need the access token you will get when you sign in
### provide emailAddress, password as request body
### send it as a post request with the Content Type header to the below route
### response will be { user: {accessToken: string, ...UserType}  } or { message: "Error info" }
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "emailAddress": "ri@gmail.com",
    "password": "12345678"
}